/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError'
export { CancelablePromise, CancelError } from './core/CancelablePromise'
export { OpenAPI } from './core/OpenAPI'
export type { OpenAPIConfig } from './core/OpenAPI'

export type { Developer } from './models/Developer'
export type { DeveloperSingle } from './models/DeveloperSingle'
export { Game } from './models/Game'
export type { GamePersonList } from './models/GamePersonList'
export type { GamePlatformMetacritic } from './models/GamePlatformMetacritic'
export { GameSingle } from './models/GameSingle'
export type { GameStoreFull } from './models/GameStoreFull'
export type { Genre } from './models/Genre'
export type { GenreSingle } from './models/GenreSingle'
export type { Movie } from './models/Movie'
export type { ParentAchievement } from './models/ParentAchievement'
export type { Person } from './models/Person'
export type { PersonSingle } from './models/PersonSingle'
export type { Platform } from './models/Platform'
export type { PlatformParentSingle } from './models/PlatformParentSingle'
export type { PlatformSingle } from './models/PlatformSingle'
export type { Position } from './models/Position'
export type { Publisher } from './models/Publisher'
export type { PublisherSingle } from './models/PublisherSingle'
export type { Reddit } from './models/Reddit'
export type { ScreenShot } from './models/ScreenShot'
export type { Store } from './models/Store'
export type { StoreSingle } from './models/StoreSingle'
export type { Tag } from './models/Tag'
export type { TagSingle } from './models/TagSingle'
export type { Twitch } from './models/Twitch'
export type { Youtube } from './models/Youtube'

export { CreatorRolesService } from './services/CreatorRolesService'
export { CreatorsService } from './services/CreatorsService'
export { DevelopersService } from './services/DevelopersService'
export { GamesService } from './services/GamesService'
export { GenresService } from './services/GenresService'
export { PlatformsService } from './services/PlatformsService'
export { PublishersService } from './services/PublishersService'
export { StoresService } from './services/StoresService'
export { TagsService } from './services/TagsService'
